service: e-commerce-app
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iamRoleStatements:
  - Effect: Allow
    Action: 
      - dynamodb:*
    Resource:
      - arn:aws:dynamodb:us-west-2:332558639130:table/LearnECommerce

functions:
  hello:
    handler: src/addCustomer.handler`
    events:
      - httpApi:
          path: /customer
          method: post

resources: 
  Resources:
    ECommerce:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LearnECommerce
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH 
plugins:
  - serverless-offline

        